# rbichewar
# TCPDUMP capture parallel from multiple hosts at a time.

# Ansible Playbook
- hosts: linuxhost
  remote_user: rushu
  become: yes
  become_method: sudo
 
  vars:
       cap_file: packet_capture_{{ ansible_hostname }}_{{ ansible_date_time['epoch'] }}.pcap


  vars_prompt:
    - name: host
      prompt: please enter remote host IP
      private: no

    - name: target_host
      prompt: please enter the target host IP
      private: no
 
    - name: dur_in_sec
      prompt: Please specify the runtime duration in sec
      private: no

    - name: interface
      prompt: Please specify the interface (e.g. eth0)
      private: no
    
    - name: dest_folder
      prompt: Please specify the destination folder (location on remote server e.g. /var/tmp/)
      private: no

    - name: filter
      prompt: Please specify the tcpdump filter (e.g. host 10.10.10.10). For no filter just press enter
      default: ""
      private: no

 
  tasks:
    - name: start tcpdump
      command: sudo /usr/sbin/tcpdump -G {{ dur_in_sec }} -W 1 -i {{ interface }} host {{ filter }} -s 0 -vw/tmp/{{cap_file}}
      register: command_output

    - debug:
             var: command_output.stdout_lines
    
    - name: copy logs
      fetch: src=/tmp/{{cap_file}} dest=/tmp/ 

    - name: remove file
      command: sudo rm -rf /tmp/{{cap_file}}

      #command: /usr/sbin/tcpdump -i {{ interface }} -s 0 -w /tmp/{{ cap_file }}
      #async: 60
      #poll: 0
 
#    - pause: minutes=1 prompt="pause for 60 seconds or press Ctrl + c then c to continue"
 
#    - name: kill tcpdump
#      command: /usr/bin/pkill tcpdump 

#    - name: compress capture file
#      command: sudo gzip {{cap_file}} chdir={{ dest_folder}}/
 
    #- name: Change file permission
    #  command: sudo chmod 755 {{ dest_folder}}/{{cap_file}}.gz

#     - name: copy logs to /export/tmp/ansible/
#       fetch: src=/tmp/{{cap_file}} dest=/tmp/

    #- name: remove files from remote server
    #  command: sudo rm -rf {{ dest_folder}}/{{cap_file}}.gz 
